import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '@/hooks/useAuth';
import { RoleProvider } from '@/hooks/roleCoontext';
export const metadata: Metadata = {
    title: 'Graduation Project',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <RoleProvider>
                        {children}
                    </RoleProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
