import type { Metadata } from 'next';
import './globals.css';
import { AuthProvider } from '@/hooks/useAuth';
import { RoomTypeProvider } from '@/hooks/usetyperoom';
export const metadata: Metadata = {
    title: 'Graduation Project',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <RoomTypeProvider>
                    <AuthProvider>
                        {children}
                    </AuthProvider>
                </RoomTypeProvider>
            </body>
        </html>
    );
}
